apiVersion: v1
kind: Pod
metadata:
  name: pausetest
spec:
  containers:
  - name: pause
    command: 
    - sleep
    args:
    - 1d
    image: busybox
    volumeMounts:
    - mountPath: /shu/root
      name: host
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory